version: '3'

services:

  app:
    container_name: blogpost
    build: .      
    env_file:
        - env.list
    ports:
      - 8081:8081
    restart: on-failure
    #environment:  
      #APP_PORT: :8081
      #API_SECRET: 77abz878cd
      #DB_HOST: host.docker.internal
      #DB_DRIVER: postgres
      #DB_USER: postgres
      #DB_PASSWORD: root
      #DB_NAME: blogPost
      #DB_PORT: 5432         
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: blogpost_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "blogPostMig"
      TZ: 'UTC'
      PGTZ: 'UTC'